### ISSUE TITLE
gulp --production breaks site

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#11]
Minifying the sites code breaks it. Common with angular.

Need to minify proof the site.

**Comment by psaunders** [comment]
Yes, if you run gulp --production when you refresh the site you get a lot of "Failed to instantiate module iserveu due to:
Error: [$injector:unpr] Unknown provider:" errors

**Comment by jalafel** [comment]
ngmin has been deprecated in favour of ng-annotate,

look into this:

https://www.npmjs.com/package/gulp-ng-annotate

**Comment by jalafel** [comment]
fiddled around with gulp-ng-annotate and it didn't seem to make any differences. Will in the future have to explicitly inject dependencies ( .controller('MainCtrl', ['$scope', function() {}]) )
