### ISSUE TITLE
Whats with the property related code?

### ISSUE THREAD

**Issue by nsweeting** [IserveU/IserveU#132]
Wondering how the code related to 'Property' ties into the platform? Half the databases seem to be devoted to it.

**Comment by psaunders** [comment]
Hey There!

People really want us to map everyone to a property (so they are YKers) and each table has a model so it's just the nature of the property data we have. Being an RDMS when you abstract a list of properties, blocks, coordianants, etc you end up with a whole bunch of tables. Hopefully with the detailed property data we'll be able to do a good job of making sure that we have a representative sample of people in a town voting.

Are you interested in helping out with that code? At the moment it has to be loaded in with a CSV but we'd like to be able to edit everything once in place without navigating through the SQL.
