### ISSUE TITLE
upload gov't issue id

### ISSUE THREAD

**Issue by jalafel** [IserveU/IserveU#143]
File upload works despite error returns. 

Two errors: 

1)  "Call to undefined method Illuminate\Database\Eloquent\Collection::delete()"
 (Then the file is uploaded) 
On second submit:
2) "SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row

If you comment out the line 149 of UserController that calls delete, this error is thrown instead: 

Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, integer given.

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/commit/1f8a83a041b4d4a35730f19a14086c26e97a2559

**Comment by jalafel** [comment]
433e44
