### ISSUE TITLE
Basic Tests

### ISSUE THREAD

**Issue by jalafel** [IserveU/IserveU#148]
Basic Tests
~~- Create/delete/edit users~~
~~- Assign permissions~~
- Get motion/edit/delete
~~- Create/delete/edit comments~~

Security Test 
- ensure no public IDs
~~- no voting without permission (if the user is not verified, doesn't have gov't id, can't vote twice)~~ 

Integrity Test
- votes match users who cast
- everything adds up correctly (vote count, comment ranks, motion ranks) 
- invalid users/vote reflected
- when profile is switched from private to public, ensure their old comments do not show their names
- comment only after a vote is cast
- comment matches vote cast

**Comment by alexialoizaga** [comment]
Security Test: ensure no public IDs . What kind of IDs can be?

**Comment by psaunders** [comment]
Ensure that if a person is set to "private" and you're not an user-administrator that you can't see anything about them.
