### ISSUE TITLE
Address Shows Some Additional Number (Unit Number?)

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#156]
![image](https://cloud.githubusercontent.com/assets/424956/10683733/574e1344-7902-11e5-81c3-c34d4e731206.png)

**Comment by psaunders** [comment]
![image](https://cloud.githubusercontent.com/assets/424956/10683749/8b0f09a4-7902-11e5-8e0b-20d4bbbfd1af.png)

**Comment by jalafel** [comment]
inherent to property data. user has ability to remove the unit if it doesn't belong to their address
