### ISSUE TITLE
Accept Terms And Conditions

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#163]
After someone accepts the terms and conditions (on clicking create) they shouldn't have to click create again.

**Comment by jalafel** [comment]
add a boolean to user profile 

so that when terms& conditions change, user needs to re-accept

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/commit/58803f872181d3c5c73d33965a4def814d354311 comes out in the array when someone logs in, I think it should be a popup over the top of everything until they accept and then it goes away until that boolean is set to 0 again.
