### ISSUE TITLE
Email mismatch on login

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#165]
When the emails don't match there isn't an error letting you know

**Comment by jalafel** [comment]
is this on create or login?

**Comment by jalafel** [comment]
e4a829fc1c8425aad382816d07143187da875490

for create. if the email doesn't exist in the database ... there's not a verbose enough message for me to parse from the API.

"Trying to get a property of a non-object" -- would that be strict enough to apply to "This email does not exist"?
