### ISSUE TITLE
Create User Post RedisException

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#180]
"errors": "Sorry, something went wrong.",
"message": "Connection refused [tcp://127.0.0.1:6379]",
"exception": "Predis\Connection\ConnectionException",

Might be something to do with my local environment, but seeing as sockets aren't critical to operations it shouldn't create a showstopping error

**Comment by jalafel** [comment]
switch over .env to include broadcast_driver = 'redis'
