### ISSUE TITLE
File Upload Progress

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#188]
If you upload a file and then hit save, the file might not be saved. Need to stop people from being able to hit "save motion" while the file is actually being uploaded.

**Comment by jalafel** [comment]
Unable to access XML objects through AngularJS limitations, they're looking into adding this feature for 1.5, I'll keep an eye on this issue: 

https://github.com/angular/angular.js/issues/1934

And try to implement something else for the time being.

**Comment by jalafel** [comment]
- on-file-submitted = " bool = true"
- on-file-success = " bool = false " 
<loading ng-show="bool"/>
