### ISSUE TITLE
Allow UI Jargon Changes

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#202]
Let people change the jargon on the site. For example, change "Motions" to "Ideas". I think it is best to do this through a dropdown so we can still translate them.

**Comment by jalafel** [comment]
UI doesn't necessarily match this so far, but integrated this in with ngTranslate config which pulls from a json array; so it's fairly easy to change system language across using hte i18n

**Comment by jalafel** [comment]
Right now it's the not the nicest interface or compatibility with the back-end.

@psaunders mentioned making it options instead of completely custom.

If we leverage ngTranslate we could change a .json completely which fills it in; but it will take awhile to set up and also create the interface.
