### ISSUE TITLE
Ecology North wishlist Item 1

### ISSUE THREAD

**Issue by MrJFlatt** [IserveU/IserveU#203]
Change wording of site so that motions become "ideas" and we have an idea bank

**Comment by MrJFlatt** [comment]
Capture peoples names & home communities, so we can track individual and unique hits, comments etc, for each idea page. Ideally we do this without making the login system unduly cumbersome

**Comment by MrJFlatt** [comment]
There will be one home page like (ISERVEU) which has FAQs, intro, why, how etc.  I picture something almost like what's on the IserveU org page with lots of photos. From there each idea will have its own page. These pages will be clearly designed with idea front and centre, similar voting and comment section (up and down cycled), but will also have space for background, relevant studies (including potentially a space for people to upload papers, studies, docs, etc.

**Comment by MrJFlatt** [comment]
Ability to add videos, audio, webinar feeds, capture twitter debates, blogs, etc. I assume to the home page and to the idea pages but I'll confirm. Would be happy to follow your advice as to what you think will look less clunky

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/issues/202
