### ISSUE TITLE
Allow Custom Pages

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#209]
Allow the creation of custom pages so there can be an about, why how or other pages. There will be one home page like (ISERVEU) which has FAQs, intro, why, how etc. I picture something almost like what's on the IserveU org page with lots of photos. Basically a rough CMS with links off the home page.

**Comment by jalafel** [comment]
add buttons to the top and unique pages added with WYISWYG, drop and drag file uploader and iframe abilities

**Comment by jalafel** [comment]
edit page drop file
ta insertlink for files on ta
