### ISSUE TITLE
Motion Sections

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#210]
Create a set of default sections, each section has a title, editor and files that can be attached. For things like background, relevant studies (including potentially a space for people to upload papers, studies, docs, etc. Motion creators can define the names of the default sections, but remove them if they wish.

**Comment by jmsyng** [comment]
@jalafel This should be removed from "low priority."

**Comment by jalafel** [comment]
This has become part of a immutable package that's shared across platforms. Custom headers is a WIP. And for ISU, the Javascript editor will also take some time to be implemented due to the robust nature of most motions, it is not high priority to have multiple section types at the moment.

**Comment by jalafel** [comment]
Hopefully can improve as Verge improves.
