### ISSUE TITLE
Home Page Embeds

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#211]
Ability to add videos, audio, webinar feeds, capture twitter debates, blogs, etc. I assume to the home page and to the idea pages but I'll confirm.

**Comment by jalafel** [comment]
Labelled as verified because the home page intro widget now acts as a WYISWYG text editor and has the ability for files, iframes and text.

**Comment by jalafel** [comment]
add edit button as admin on diff pages

**Comment by jmsyng** [comment]
@jalafel Embeds do not appear to be working. The YouTube embeds appear as an image. Vimeo iframe embeds don't work.

**Comment by jalafel** [comment]
@jmsyng so the WYSIWYG editor that we are using sanitizes the iframes from the textarea. Meaning it strips the iframe tag and anything within it. It's relaly annoying. I've spent a few hours trying to find a work around and it just might be better to move to a different editor. However, for the time being, if you post the iframe in the settings.json it will work. Sorry about that.

**Comment by psaunders** [comment]
What we have seems to work now. You can add videos and pictures, not a lot of options to configure but that's OK.
