### ISSUE TITLE
"Your identity has not been authorized"

### ISSUE THREAD

**Issue by philipb** [IserveU/IserveU#212]
This may just be a Philip issue, don't know.
I logged in to https://yk.iserveu.ca
I cliced on 'Currently Passing'
Read the motion, scrolled down to Voting
Moused over the thumbs, a red 'no-go' graphic showed.  A text thing said "Your identity has not been authorized.  Once you fill in your user details, authorization will take only a short moment."
There was no indication of how to fill in my user details, and as best I know, my identity has been authenticated.

**Comment by jalafel** [comment]
Doing a large refactor, will test this issue afterewards.

**Comment by psaunders** [comment]
Not really the way we're doing things for now, safe to close
