### ISSUE TITLE
"You haven't vote, yet" on homepage should read "You haven't voted, yet."

### ISSUE THREAD

**Issue by mwestwick** [IserveU/IserveU#227]

**Comment by ikesaunders** [comment]
Sorry to be nitpicky, but I think the comma is unnecessary, and even sounds a little threatening.

**Comment by mwestwick** [comment]
Despite the fact that this is grammatically correct, I tend to agree with Ike on the threatening item.

**Comment by jalafel** [comment]
@mwestwick i stared at this for a good minute before i saw the difference
