### ISSUE TITLE
"My Motions" are not showing up after being submitted as drafts

### ISSUE THREAD

**Issue by mwestwick** [IserveU/IserveU#230]

**Comment by jalafel** [comment]
can you screen cap what you see?

**Comment by jalafel** [comment]
posting to: /api/motion?status=0&user_id=6 as JUST a citizen

<img width="625" alt="screen shot 2016-05-04 at 12 55 26 pm" src="https://cloud.githubusercontent.com/assets/12400507/15022027/b437a3b6-11f7-11e6-931b-b0a5bf314d4f.png">

@psaunders
