### ISSUE TITLE
UI hanging when navigating between motions.

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#232]
Seemingly inconsistently, new motions fail to load when I click between them.

Console errors are a mix of:

Failed to load resource: net::ERR_FAILED 

and

angular.js:11756 GET http://yk.iserveu.ca/api/motion/7/motionfile net::ERR_CONNECTION_TIMED_OUT

![image](https://cloud.githubusercontent.com/assets/11844404/15064118/0ca7c4ec-130e-11e6-9958-931d7701e6c8.png)

**Comment by psaunders** [comment]
Write frontend test that opens one motion after another.
Expects: Loading icon to show
Expects: No longer than 3 second wait

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/pull/504
