### ISSUE TITLE
Can my password also be remembered when I click "create"?

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#233]
It appears as if my email address is stored and carried over to the next form, but I have to re-enter my password as well.

![image](https://cloud.githubusercontent.com/assets/11844404/15064188/f0c172b8-130e-11e6-999f-f05a08fdc72f.png)

![image](https://cloud.githubusercontent.com/assets/11844404/15064197/03d110e8-130f-11e6-9841-3679319d7be5.png)

**Comment by psaunders** [comment]
@ikesaunders ... Why don't you try implementing this, it sounds pretty easy unless angular has some weird thing about 2way binding on password boxes

**Comment by psaunders** [comment]
The default is for a session and local storage, so this is basically happening anyway
