### ISSUE TITLE
Add Text Search To Motion

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#235]
Typing various two letter strings can cause the "Bye to unit 407" motion to show up, despite them not showing up anywhere in the motion.

For instance, 'ad'

![image](https://cloud.githubusercontent.com/assets/11844404/15064408/2bd9e162-1311-11e6-873f-ff4bba9de8a3.png)

**Comment by psaunders** [comment]
There actually aren't text searches. Should bring in querying system and add that.
