### ISSUE TITLE
How can I reset password?

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#238]
Currently I just get a "something went wrong" error if I enter the incorrect input, so I can't tell if it's my password that's wrong or if the site's malfunctioning. 

Additionally, even if _was_ my password that  was incorrect, I have no way of resetting it from the front end.

**Comment by psaunders** [comment]
I've fixed this on the backend, is it working front end @jalafel

**Comment by jalafel** [comment]
@psaunders I get a 404 when i click the email link
