### ISSUE TITLE
Terms and Conditions button and accept box enters :hover state inconsistently

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#239]
Unhovered, unclicked, the button appears to be active:

![image](https://cloud.githubusercontent.com/assets/11844404/15064614/79e005ec-1313-11e6-93da-c7e82a28a6f3.png)

Clicking on it lightens it, but then the "I Agree" box darkens. 

![image](https://cloud.githubusercontent.com/assets/11844404/15064625/929b49e8-1313-11e6-8c57-2c008f92851d.png)

Also, this is a separate issue, but 3 tickets for the T&C box seems like overkill. Is there any way to get rid of the scrollbar on the right when you open the modal?

![image](https://cloud.githubusercontent.com/assets/11844404/15064656/fd6d802e-1313-11e6-8a1f-9618919faf05.png)

**Comment by jalafel** [comment]
unfortunately this is an angular material issue, i'll look into it some more but very low priority
