### ISSUE TITLE
What does the virus icon represent in the context of the motion information on the right?

### ISSUE THREAD

**Issue by ikesaunders** [IserveU/IserveU#240]
![image](https://cloud.githubusercontent.com/assets/11844404/15064764/50272d3c-1315-11e6-964f-52949f7f442a.png)

Hovering over it doesn't reveal anything new. What does it indicate?

**Comment by jalafel** [comment]
it's an iserveu stamp. we stamp everything. everybody. i mean look at paige and dane. iserveu certified.

**Comment by psaunders** [comment]
It was a placeholder for departments once, I don't know why it's stamped there
