### ISSUE TITLE
motion.comments should always return object or array

### ISSUE THREAD

**Issue by jalafel** [IserveU/IserveU#246]
can we make this a stricter contract between the server and client? 

API is returning either an array or json object depending when there are/aren't motion comments. It's better if it did the same as every other api endpoint and always returned just one type.

**Comment by jalafel** [comment]
still happening -- and on motion.votes as well

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/commit/10beb15132366e8929915ed3c40bb2c4405e9b88

Test passes, it's JSON each time. The server isn't getting a header or something that is making it think that you are not doing an AJAX call.
