### ISSUE TITLE
Change Email Editor from WYSIWYG to Textarea

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#270]
Allow user to customize logo/text and maybe then do a preview?

**Comment by psaunders** [comment]
I can add in the logo to the new messaging system

**Comment by psaunders** [comment]
The edit does work, but it needs to be a textarea instead of a WYSIWYG editor (p tags etc are escaped now)

**Comment by psaunders** [comment]
![image](https://cloud.githubusercontent.com/assets/424956/20040772/51bb35a6-a42b-11e6-843e-44cc0d16b9b6.png)
