### ISSUE TITLE
On Settings.json@verify_citizens: false does not return permissions on register

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#309]
when you create a new user with verify_citizens off, it returns you an empty permissions array

**Comment by psaunders** [comment]
Well yeah, they have no permissions. They should still be able to see things, just not do anything

**Comment by jalafel** [comment]
what i mean is when they log back out and back in  they'll be able to do stuff

**Comment by jalafel** [comment]
it's when verify_citizens === false // intended for localized and demo, like immmediate voting and stuff

**Comment by psaunders** [comment]
This fixed now?

**Comment by jalafel** [comment]
@psaunders  Unless it's in the Comment index PR, not working in local:

![screen shot 2016-09-18 at 11 37 28 am 2](https://cloud.githubusercontent.com/assets/12400507/18616980/63f9c25e-7d94-11e6-901b-be44c6963ff6.png)
