### ISSUE TITLE
Telephone user field

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#321]
Should we have a telephone field for users to contact them?

**Comment by psaunders** [comment]
Is "them" the people running the website? I think we should have a string that goes at the bottom on the site which lets people put in whatever they decide is a priority in the footer, could be an address or two phones, or a fax

**Comment by jessicaquynh** [comment]
For every user. Not sure who them is.

**Comment by psaunders** [comment]
Backend now has this:
https://github.com/IserveU/IserveU/pull/418/commits/bf664ae42062ef3754d22316aedbaeb25e0d1d5a
