### ISSUE TITLE
Getting analytics var dump before article load

### ISSUE THREAD

**Issue by jalafel** [IserveU/IserveU#324]
![screen shot 2016-09-26 at 1 13 58 pm 2](https://cloud.githubusercontent.com/assets/12400507/18844423/3556a234-83eb-11e6-95f0-5f5cb0684127.png)
This is happening on my local as admin@vergecomms.ca

On article show, it will first display this and then load correctly.

**Comment by psaunders** [comment]
Hmm. I think this is from another world
