### ISSUE TITLE
Image preview not show in motion 

### ISSUE THREAD

**Issue by vinhtruong94** [IserveU/IserveU#355]
![image](https://cloud.githubusercontent.com/assets/10766052/19659811/561d709e-99fb-11e6-91e0-73d431d0fac4.png)
No preview of the image.
![image](https://cloud.githubusercontent.com/assets/10766052/19659853/89280846-99fb-11e6-999b-6a4e858506f3.png)
But preview for pdf is correct.

**Comment by Kiniamaro** [comment]
fixed in my branch
