### ISSUE TITLE
Verify User to Vote/Comment Setting

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#361]
Don't do the "add permission" thing, just have the permission check not required when the setting is on so that people can be added as citizens.

**Comment by jessicaquynh** [comment]
@psaunders What's the backend key for this?

**Comment by psaunders** [comment]
I think we need to add a role for this that isn't citizen and apply this role to people, like a "participant" role. Both participants and citizens can cast votes, but you can take away the permission to create votes from participants. And when people first sign up, the won't have even the permission attribute.

I can use the notification system to send an email to admins allowing them to quickly click a button that gives them the role of partipant. Citizen though is an auto-role that gets applied when they have the combo of valid id and a verified address.
