### ISSUE TITLE
Unauthenticated Catch

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#366]
![image](https://cloud.githubusercontent.com/assets/424956/19667087/c001b4b8-9a1c-11e6-9697-a771eb5d8d3d.png)

I think a lot of these glitches are having because the user thinks that it is authenticated but it's not. In this case it is showing a 401, so the user should be redirected to the login screen.

**Comment by jessicaquynh** [comment]
https://github.com/IserveU/IserveU/blob/master/public/app/shared/config/httpProvider.conf.js#L49

Should already be happening, can anyone verify this still as an issue?
