### ISSUE TITLE
Add redis to the requirements

### ISSUE THREAD

**Issue by Kiniamaro** [IserveU/IserveU#384]
![2016-10-26-153507_341x94_scrot](https://cloud.githubusercontent.com/assets/3664099/19742177/c97ba5be-9b91-11e6-91c3-f4eacdc2490e.png)

**Comment by psaunders** [comment]
Yeah that is a separate install in the laravel docs for some reason, easy fix

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/wiki/Setting-up-Your-Server
