### ISSUE TITLE
Submitting multiple setting keys gives an error

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#389]
Trying to post multiple keys at once, 

and sometimes I get a 400 for a missing key.

However, the request payload in the header clearly has data in it.

![screen shot 2016-10-26 at 6 23 53 pm 2](https://cloud.githubusercontent.com/assets/12400507/19747381/6333f83e-9ba9-11e6-8d5d-e09b55a8e8bf.png)

**Comment by jessicaquynh** [comment]
Oh hah, i see. it's an error for an invalid key. Got it

**Comment by psaunders** [comment]
Yeah, can't see A600 in there bros
