### ISSUE TITLE
Invalid JSON in settings.json on patch

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#392]
![screen shot 2016-10-26 at 8 13 57 pm 2](https://cloud.githubusercontent.com/assets/12400507/19749672/c90ea974-9bb8-11e6-9920-835b02a73721.png)

**Comment by psaunders** [comment]
That means settings.json got corrupted. Can you delete it and recreate? Then if this comes up again let me know what was posted to cause the corruption
