### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#398]
Error coming up as I browse. Is it supposed to be "Motion not Found?"

![image](https://cloud.githubusercontent.com/assets/424956/19752685/4e9479c0-9bcd-11e6-81ee-62a743edac1b.png)

**Comment by jessicaquynh** [comment]
This 404 is coming in because it's trying to get the department icon, and it gets a 404. I think I'll just take it out, since we are Single Page anyway, probably won't be getting a 404 on much.

**Comment by jessicaquynh** [comment]
Actually, if there's a way the server can differentiate between a page request versus this, that would be a good way to handle this.

**Comment by jessicaquynh** [comment]
I've just removed this, there's really no functionality for it right now in a SPA until there's a more verbose server error for the client to handle.
