### ISSUE TITLE
Updating department throws 500

### ISSUE THREAD

**Issue by jessicaquynh** [IserveU/IserveU#411]
![screen shot 2016-10-27 at 4 33 37 pm](https://cloud.githubusercontent.com/assets/12400507/19784273/2571fe96-9c63-11e6-9da4-a94ba060f4f6.png)

**Comment by psaunders** [comment]
I'll have to write tests for it, it never got done beyond the index method

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/pull/414
