### ISSUE TITLE
Closing Date Missing

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#444]
it didn't stick, or something

![image](https://cloud.githubusercontent.com/assets/424956/19838046/03e72648-9e9d-11e6-86da-66f109d366d6.png)

**Comment by Kiniamaro** [comment]
it's missing from the motion view too
![2016-11-08-152512_880x463_scrot](https://cloud.githubusercontent.com/assets/3664099/20115770/8dc0b2cc-a5c7-11e6-849c-c146aeca6ba5.png)

**Comment by psaunders** [comment]
There is a setting I think called "No closing" or something, which is a good setting to have and might be the issue here. But if it's off, it should be off for both back and front end.

**Comment by Kiniamaro** [comment]
wrong variable names were the cause of this issue.
