### ISSUE TITLE
Two Save Buttons

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#454]
Also remove the theme field, that isn't doing anything.

There are two save buttons. Probably a good idea to get @ikesaunders feedback on how to lay this out. For one thing I think the colors in the fields when you customize should be pre-populated with the defaults so you know what you're changing

![image](https://cloud.githubusercontent.com/assets/424956/19864171/68b8d528-9f6d-11e6-92e2-68edffb7ad3a.png)

**Comment by psaunders** [comment]
This does save, it just causes errors (probably from saving multiple times)

**Comment by vinhtruong94** [comment]
![image](https://cloud.githubusercontent.com/assets/10766052/24312211/e90db584-10ad-11e7-9c1a-ca6b8c4ac535.png)
This error ? 
@psaunders  
I removed one of the save button already, but was not managed to save ( my preset theme is purple, I try to customize ) 
I am looking in to this error now
