### ISSUE TITLE
Iphone rendering issue (5S - IOS 7)

### ISSUE THREAD

**Issue by Kiniamaro** [IserveU/IserveU#458]
![2016-10-31-163657_366x625_scrot](https://cloud.githubusercontent.com/assets/3664099/19870738/47cd2574-9f88-11e6-8dd8-7edf94c44b2c.png)

**Comment by Kiniamaro** [comment]
IOS 8 does it too

**Comment by Kiniamaro** [comment]
IOS 9 and up are good

**Comment by psaunders** [comment]
Sam claims to have iOS 9 and can't get past the login screen @Kiniamaro

**Comment by Kiniamaro** [comment]
@psaunders what's his device?

**Comment by psaunders** [comment]
iPhone 5
