### ISSUE TITLE
Motion Data Remains Visible 

### ISSUE THREAD

**Issue by mwestwick7** [IserveU/IserveU#461]
I created a draft motion, saved it as a draft, then wanted to delete the motion. I selected the trash icon, confirmed I wanted to "Destroy Motion," received a prompt saying "motion destroyed," but the motion still appeared in the UI. 

Upon refreshing the page, the data disappeared as per command, but this is obviously not a desirable user experience.

**Comment by psaunders** [comment]
Sounds like the menu isn't in sync with the actions of the delete button
