### ISSUE TITLE
Votes The Same

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#462]
After disagreeing and commenting on a motion, all motions seem to have the same 2 downvotes

![image](https://cloud.githubusercontent.com/assets/424956/19946687/5bd209b0-a11b-11e6-9202-17efd57e28a4.png)

**Comment by Kiniamaro** [comment]
yeah there seems to be a big refresh issue going on with the motions

**Comment by Kiniamaro** [comment]
umm, This might have been fixed when I made the calendar tile show up again. I can't seem to be able to reproduce this on my local
