### ISSUE TITLE
add setting for default anonymous comment name

### ISSUE THREAD

**Issue by Kiniamaro** [IserveU/IserveU#475]
Right now everyone is called "Yellowknifer" this works for the yk site but won't do once we have multi-tenancy, 

this can easily be fixed by adding a setting to the settings.json with what the anonymous name should be.

**Comment by psaunders** [comment]
I think what we want to do is add a col to the community table for the "From the town" name. Like Montrealer/Vancouverite/Torontonian etc at the same time as adding direct anonymity controls to the actual posting of the comment (it makes privacy so much easier to police) and sometimes you want to show your name, sometimes you don't (Your whistle blowing).

**Comment by psaunders** [comment]
Back end done: https://github.com/IserveU/IserveU/pull/555

**Comment by psaunders** [comment]
Front seems to be done on this.
