### ISSUE TITLE
Heading Nesting

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#477]
Dash should look like this:
![image](https://cloud.githubusercontent.com/assets/424956/20198530/2f5a92d6-a773-11e6-9b8d-63dd5f3c79c0.png)

Not this:
![image](https://cloud.githubusercontent.com/assets/424956/20198567/4d22614a-a773-11e6-8deb-801d11509926.png)

**Comment by Kiniamaro** [comment]
just to be sure, you mean the dashboard shouldn't have the top tabs like `CONTENT` `SYSTEM` etc... ?
