### ISSUE TITLE
g.get is not a function

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#480]
Shows up when not logged in on live site

![image](https://cloud.githubusercontent.com/assets/424956/20250230/e8e39afa-a9d9-11e6-8583-fd216058dfca.png)

**Comment by psaunders** [comment]
Dane has got this too and no motions are loading

**Comment by Kiniamaro** [comment]
this seems to be fixed on master

**Comment by Kiniamaro** [comment]
ok I ran npm on yk and that fixed it. so my guess is yarn isn't doing everything that npm does

**Comment by Kiniamaro** [comment]
This was determined to be an issue with the `--production` flag when running `gulp`

**Comment by psaunders** [comment]
@jessicaquynh do you know this one?
