### ISSUE TITLE
Vote Front End

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#508]
The vote bar changes but the icon on the right does't  if a motion is passing or failing

**Comment by Kiniamaro** [comment]
it changes for me, only thing that doesn't change is if you vote abstain, but abstain votes don't count so it's intended behavior?

I'll need more info on this.

**Comment by psaunders** [comment]
Yeah it's passing the tests I wrote: https://github.com/IserveU/IserveU/pull/531
