### ISSUE TITLE
Comment Votes

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#633]
Comment votes aren't remembered after voting and doing a refresh.

It's like the commentvote model for the user isn't being populated anymore as the user was expecting. 
- Could it be related to using slugs instead of IDs more?

If it takes too long we should just be pulling from /user/X/commentvotes by the motion to get the comment votes for a specific user on this motion rather than trying to merge a big array of all the comment votes. It would only take 30 minutes to write and test this in the API.

**Comment by Kiniamaro** [comment]
This seems to be fixed, can someone else confirm?

@psaunders @vinhtruong94
