### ISSUE TITLE
TypeError: this[0].focus is not a function

### ISSUE THREAD

**Issue by vinhtruong94** [IserveU/IserveU#634]
Appear on console after pressing close on term and conditions policy pop-up in local environment

**Comment by Kiniamaro** [comment]
screenshots please.

**Comment by vinhtruong94** [comment]
![image](https://cloud.githubusercontent.com/assets/10766052/22128702/f0f9327a-de6f-11e6-8139-32a2e711f0a2.png)
![image](https://cloud.githubusercontent.com/assets/10766052/22128712/f987c9a6-de6f-11e6-9afd-1c0a493bf483.png)

**Comment by psaunders** [comment]
I can't get this to happen. If you can't consistently get this Vinh let's close it

**Comment by psaunders** [comment]
Saw this yesterday

**Comment by vinhtruong94** [comment]
#735
