### ISSUE TITLE
Local Storage Issue

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#639]
The user record in local storage isn't being updated when the user accepts the terms of service (or probably if they change their name either)

**Comment by vinhtruong94** [comment]
user record in local storage = local database?

**Comment by Kiniamaro** [comment]
@vinhtruong94 kinda yeah.

**Comment by psaunders** [comment]
I talked with @jessicaquynh this morning and I believe she has been trying to move away from using local storage (it was more trouble than it's worth) so perhaps you should try to strip it out
