### ISSUE TITLE
Large Number of Motion Files

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#664]
The Motion is showing a lot of motion files:
http://theideasbank.ca/#/idea/26

But only two on the back end. If they're versions of other files the should be stacked under them.

**Comment by Kiniamaro** [comment]
![2017-02-19-164548_359x208_scrot](https://cloud.githubusercontent.com/assets/3664099/23106933/e41e3aa8-f6c2-11e6-8438-794a336826a8.png)

you can delete files on master,

not on the current ideasbank, this can be fixed if they delete the old version of the resources and upload the new one.

OR

put the images in the body of the motion, where images should be.

**Comment by psaunders** [comment]
These replacement files are supposed to "stack" assuming the API works the same way it did before. It's probably the replacement/versioning that is causing the issue. The files that replace parents should be hidden by default with a "see earlier revisions" expander.

You could try logging into the ideas bank @Kiniamaro and deleting the files to see if something else is going on.

Benefit of the doubt, it could be permissions on the storage directory if it's not the older revisions?

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/pull/698
