### ISSUE TITLE
Ideas Bank: Registered Users

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#677]
Also the page where we see who has registered is gone?  We can't see it.  Used to be able to.

**Comment by psaunders** [comment]
![screen shot 2017-02-04 at 5 11 42 pm](https://cloud.githubusercontent.com/assets/424956/22621920/11b04f32-eafd-11e6-8ef1-39b7706d0b0d.png)

**Comment by Kiniamaro** [comment]
![2017-02-04-184701_1287x729_scrot](https://cloud.githubusercontent.com/assets/3664099/22622521/6124d17a-eb0a-11e6-81d3-3c15ac7e1359.png)

?

otherwise I'll need an account on the ideasbank @psaunders
