### ISSUE TITLE
Blank: Your Comments

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#685]
![image](https://cloud.githubusercontent.com/assets/424956/22719559/0c0c78e8-ed74-11e6-8d65-020f98ea25f2.png)

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/pull/690

**Comment by Kiniamaro** [comment]
![2017-02-19-143145_567x85_scrot](https://cloud.githubusercontent.com/assets/3664099/23105631/27a9622e-f6b0-11e6-9135-3fcf5dab6059.png)
