### ISSUE TITLE
Issue with Ideas bank

### ISSUE THREAD

**Issue by EcologyNorth501351** [IserveU/IserveU#687]
There are a couple of other questions too.  A user came in yesterday because he was frustrated with the program.

Here are his comments:
He tried to submit an idea and wrote it all up but there was no way to submit it, the little icon started swirling and there wasn't any follow-up.  He gave up frustrated, and came by to ask for help.

So can we make it possible that when someone saves their idea, a message pops up saying "Thank you your idea has been submitted, Ecology North staff will read and may edit your idea, check back soon to see your idea in the bank.  The Ideas Bank will be in touch with you shortly"

Than we need that idea to be sent to us or appear in the ideas section, or an email that an idea was created??  How would that happen?

Also He couldn't choose the category, went to environment automatically (is there a way to allow people to choose category

Also the date that it closes (we don't want that there - a relic of IServeU) please remove

As Lyle mentioned the user roles, citizen participant etc. are irrelevant to us.  Can people just automatically be citizens, and have full activity on site.   Now we have to change them to citizen or they can't see anything.  Very frustrating!  Please remove this whole section.

We wanted to delete the Criteria page (we don't seem to be able to do that)

And as Lyle noted photos don't get attached

Thanks Paige, 

We looked at the GitHub thing, but didn't know where to put these comments, any advice for using that? Which section do we use?  Is there any structure to commenting

**Comment by vinhtruong94** [comment]
You may want to create a New Issue by clicking on New Issue for each problem here so we can separate tasks for our colleague next time.

**Comment by vinhtruong94** [comment]
Have you tried accessing to Site Admin> Pages >  
There is an option to delete Criteria page there.
Please comment if it has not been deleted, we will open an issue about deleting pages
Thanks.

**Comment by psaunders** [comment]
Yeah it's hard to address the individual issues when they're all in one issue like this. There is also an option to turn on or off the closing dates. Is that not working?

**Comment by EcologyNorth501351** [comment]
vinhtruon94, I have tried many times to remove the page, it seems to say page destroyed, and it still remains there.

**Comment by psaunders** [comment]
Resubmit as individual issues if it's still an issue
