### ISSUE TITLE
getRankTitle() Being Passed Undefined

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#696]
This has an intermittent failure in the protractor test. May be the cause, the function is being alternately passed the actual rank and an undefined value a million times. Can't be good, should just be triggered on a state change.

![image](https://cloud.githubusercontent.com/assets/424956/23103843/b99bfb2c-f68f-11e6-9f4f-ae800cf09460.png)

**Comment by vinhtruong94** [comment]
this happens when we access to a motion ?

**Comment by psaunders** [comment]
If you log the function called to calculate the thumbs up/down. It seems to me like it should only be run once when the motion starts and when the user votes.
