### ISSUE TITLE
Abstain comment copy issue

### ISSUE THREAD

**Issue by mwestwick7** [IserveU/IserveU#721]
![motion issue](https://cloud.githubusercontent.com/assets/23155660/23594324/6ac9d79c-01d6-11e7-8c0d-0a0d0a3d425e.png)

On all motions, the "abstain" comment section says "no comments have been made for agree"

**Comment by psaunders** [comment]
alt+printscreen does just the current window BTW Westwick.

Fixed in: https://github.com/IserveU/IserveU/pull/722
