### ISSUE TITLE
Draft Motion Vote Feedback

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#729]
Smaller detail but when you vote on a draft or review motion
- [x] It shouldn't say "this motion is closed for voting" it should either not show the voting buttons or show the message "Motion must be published to vote on it
- [x] The vote bar showed up below when I clicked, it shouldn't show up.

![image](https://cloud.githubusercontent.com/assets/424956/23818648/32aed148-05cb-11e7-962e-6599fdc73eb6.png)

**Comment by vinhtruong94** [comment]
![image](https://cloud.githubusercontent.com/assets/10766052/24309888/fd63abc4-10a3-11e7-8381-ca50271c4781.png)

**Comment by vinhtruong94** [comment]
https://github.com/IserveU/IserveU/pull/741
