### ISSUE TITLE
Accept Terms and Conditions

### ISSUE THREAD

**Issue by psaunders** [IserveU/IserveU#735]
When you're logged in as a citizen/participant it never seems to go away on any refresh. It should be saving the date into the DB, but if that date is set that should be the end of it.

**Comment by vinhtruong94** [comment]
this seems to not occur when user/customers use it, it may have occurred in testing process. I was not seeing this error when I'm accessing the site as admin,participant or citizen so this issue should be keep open in case we meet it again in the future.

**Comment by psaunders** [comment]
This is being caused by the local storage/cached user not being updated. POST and DB are working fine.
