### ISSUE TITLE
Can't attach more than on photo to an "idea" page/post

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#757]
Posting more than one photo is slow, and multiple photos tend to morph into all showing the same image. More than three photos on a idea page and it won't let you save the idea.

**Comment by psaunders** [comment]
May also be resolved with the big file upload rework:
https://github.com/IserveU/IserveU/pull/698

**Comment by Kiniamaro** [comment]
Fixed by #807
