### ISSUE TITLE
closing date unnecessary

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#758]
When creating an idea, at the bottom, there is a pull down calendar to select a closing date for the idea, but we don't need that and it just makes things confusing. We should remove this option to set a closing date altogether.

**Comment by vinhtruong94** [comment]
Can you go to Setting > Site Admin and choose the System option ? Then click on pencil icon of Ideas, there will be Closing Date Behahiour option, uncheck the box and next time you create an idea the closing date option will be off. 
![image](https://cloud.githubusercontent.com/assets/10766052/25774798/a63ef172-3264-11e7-8d18-1d2872ce4fcb.png)

**Comment by vinhtruong94** [comment]
that little checked box in the picture
