### ISSUE TITLE
Images attached to an idea appear at the bottom as attachments

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#759]
Since you can't actually copy and paste an image into the text of an idea page/post, you have to attach the actual image file to the page, which shows up at the bottom of the idea post as an attachment. We want to be able to attach files at the end of the post, and have pictures and figures throughout the text, but we don't want the picture files (.jpeg, .png, etc) to show up as attachments at the end of the post as well.

**Comment by psaunders** [comment]
Currently being worked on by @Kiniamaro 

https://github.com/IserveU/IserveU/pull/698
