### ISSUE TITLE
Problem Accessing Idea Editing Page

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#774]
The editing page won't show up when I click the edit icon (pencil) on an idea page under an admin account. this message shows up instead: 
app/components/motionForm/motionForm.tpl.html

![untitled](https://cloud.githubusercontent.com/assets/25375910/26365511/108a15f0-3fa5-11e7-8b28-e2a984b55495.png)

**Comment by psaunders** [comment]
This might be related to the route being edit-idea instead of edit-motion.

**Comment by psaunders** [comment]
https://github.com/IserveU/IserveU/pull/775
