### ISSUE TITLE
IdeasBank webpage editing mode warning for users

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#800]
I put in an issue request regarding newly generated "ideas" yesterday and today the site isn't working as it should. I suspect the site is being worked on. Is it possible to get a warning to users that the "site is currently under maintenance, please check back again shortly" or something to this effect.
Thank you for your time and expertise, much appreciated!
Catherine

**Comment by psaunders** [comment]
We weren't doing updates, we do have a message for that. 

We have a message that we recommend using, you can edit it under this section of the control panel.

![image](https://user-images.githubusercontent.com/424956/32144064-9b158f0e-bc89-11e7-9d11-38ca2f0245a3.png)
