### ISSUE TITLE
Ideas Bank not functioning overall

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#804]
The general functions of the site are not working with some specific known examples listed below:
1. List of ideas (right-hand side of main page) no longer appearing.
2. Image on main page not appearing.
3. Cannot make/save any updates to any content.
4. A user had posted a draft idea but it doesn't appear for administrators to approve.

Thank you,
Catherine

**Comment by psaunders** [comment]
Caused by a 500 error on the site (error logs over backup cron job), fixed that.
