### ISSUE TITLE
IdeasBank - Login required to browse site

### ISSUE THREAD

**Issue by EcologyNorth** [IserveU/IserveU#805]
Hi tech guru,

It is currently a requirement to login or create an account before browsing the site. Can this be changed? We would like users to be able to see what the site is about then create an account to post any ideas/comments.
Any insight would be wonderful! And thank you for everything :)

**Comment by psaunders** [comment]
There's a setting for this that got added but it seems to have stopped functioning.

**Comment by Kiniamaro** [comment]
Fixed by  #810
